ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = TRUE;
-- load_and_build.sql : runs AFTER files are uploaded by run_all.sh
USE ROLE PORTPILOT_ENGINEER;
USE WAREHOUSE PORTPILOT_LOAD_WH;
USE SCHEMA PORTPILOT.RAW;

-- ---------- LOAD RAW ----------
CREATE OR REPLACE TABLE RAW.DIM_CUSTOMER USING TEMPLATE (SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) WITHIN GROUP (ORDER BY ORDER_ID) FROM TABLE(INFER_SCHEMA(LOCATION => '@RAW.LANDING/dim_customer.csv.gz', FILE_FORMAT => 'RAW.CSV_GZ')));
COPY INTO RAW.DIM_CUSTOMER FROM @RAW.LANDING/dim_customer.csv.gz FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_GZ') MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

CREATE OR REPLACE TABLE RAW.DIM_VESSEL USING TEMPLATE (SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) WITHIN GROUP (ORDER BY ORDER_ID) FROM TABLE(INFER_SCHEMA(LOCATION => '@RAW.LANDING/dim_vessel.csv.gz', FILE_FORMAT => 'RAW.CSV_GZ')));
COPY INTO RAW.DIM_VESSEL FROM @RAW.LANDING/dim_vessel.csv.gz FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_GZ') MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

CREATE OR REPLACE TABLE RAW.FACT_CONTAINER_JOURNEY USING TEMPLATE (SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) WITHIN GROUP (ORDER BY ORDER_ID) FROM TABLE(INFER_SCHEMA(LOCATION => '@RAW.LANDING/fact_container_journey.csv.gz', FILE_FORMAT => 'RAW.CSV_GZ')));
COPY INTO RAW.FACT_CONTAINER_JOURNEY FROM @RAW.LANDING/fact_container_journey.csv.gz FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_GZ') MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

CREATE OR REPLACE TABLE RAW.FACT_CONTAINER_EVENT USING TEMPLATE (SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) WITHIN GROUP (ORDER BY ORDER_ID) FROM TABLE(INFER_SCHEMA(LOCATION => '@RAW.LANDING/fact_container_event.csv.gz', FILE_FORMAT => 'RAW.CSV_GZ')));
COPY INTO RAW.FACT_CONTAINER_EVENT FROM @RAW.LANDING/fact_container_event.csv.gz FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_GZ') MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

CREATE OR REPLACE TABLE RAW.FACT_DELAY_EVENT USING TEMPLATE (SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) WITHIN GROUP (ORDER BY ORDER_ID) FROM TABLE(INFER_SCHEMA(LOCATION => '@RAW.LANDING/fact_delay_event.csv.gz', FILE_FORMAT => 'RAW.CSV_GZ')));
COPY INTO RAW.FACT_DELAY_EVENT FROM @RAW.LANDING/fact_delay_event.csv.gz FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_GZ') MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

CREATE OR REPLACE TABLE RAW.ADVISORY_DOCUMENTS USING TEMPLATE (SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) WITHIN GROUP (ORDER BY ORDER_ID) FROM TABLE(INFER_SCHEMA(LOCATION => '@RAW.LANDING/advisory_documents.csv.gz', FILE_FORMAT => 'RAW.CSV_GZ')));
COPY INTO RAW.ADVISORY_DOCUMENTS FROM @RAW.LANDING/advisory_documents.csv.gz FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_GZ') MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- ---------- BUILD GOVERNED LAYER ----------
USE WAREHOUSE PORTPILOT_WH;

CREATE TABLE IF NOT EXISTS PORTPILOT.GOVERNANCE.CUSTOMER_ACCESS (role_name STRING, customer_id STRING);
DELETE FROM PORTPILOT.GOVERNANCE.CUSTOMER_ACCESS;
INSERT INTO PORTPILOT.GOVERNANCE.CUSTOMER_ACCESS VALUES
  ('PORTPILOT_CUSTOMER_SUCCESS','MERIDIAN_CHEMICALS_GMBH'),
  ('PORTPILOT_CUSTOMER_SUCCESS','CUSTOMER_002'),
  ('PORTPILOT_CUSTOMER_SUCCESS','CUSTOMER_003');

CREATE OR REPLACE SECURE VIEW PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY AS
SELECT j.container_id, j.booking_date, j.customer_id,
  c.tier AS customer_tier,
  CASE WHEN IS_ROLE_IN_SESSION('PORTPILOT_OPS_ANALYST') OR IS_ROLE_IN_SESSION('PORTPILOT_AUDITOR')
       THEN c.contact_email ELSE '***MASKED***' END AS contact_email,
  j.trade_lane, j.vessel_id, j.on_time_delivery, j.delay_hours, j.documentation_late,
  j.routed_through_sgsin, WEEKISO(j.booking_date) AS iso_week
FROM PORTPILOT.RAW.FACT_CONTAINER_JOURNEY j
JOIN PORTPILOT.RAW.DIM_CUSTOMER c ON c.customer_id = j.customer_id
WHERE IS_ROLE_IN_SESSION('PORTPILOT_OPS_ANALYST') OR IS_ROLE_IN_SESSION('PORTPILOT_EXEC')
   OR IS_ROLE_IN_SESSION('PORTPILOT_AUDITOR') OR IS_ROLE_IN_SESSION('PORTPILOT_ENGINEER')
   OR EXISTS (SELECT 1 FROM PORTPILOT.GOVERNANCE.CUSTOMER_ACCESS a
              WHERE a.customer_id = j.customer_id AND a.role_name = CURRENT_ROLE());

CREATE OR REPLACE SECURE VIEW PORTPILOT.SEMANTIC.V_DELAY_EVENT AS
SELECT d.container_id, d.cause_code, d.delay_hours, d.event_date,
       WEEKISO(d.event_date) AS iso_week, j.trade_lane
FROM PORTPILOT.RAW.FACT_DELAY_EVENT d
JOIN PORTPILOT.RAW.FACT_CONTAINER_JOURNEY j ON j.container_id = d.container_id;

CREATE OR REPLACE TABLE PORTPILOT.SEMANTIC.EVENT_VOLUME_DAILY AS
SELECT TO_DATE(event_at_utc) AS event_day, source_system, event_type, COUNT(*) AS event_count
FROM PORTPILOT.RAW.FACT_CONTAINER_EVENT GROUP BY 1, 2, 3;

USE ROLE SECURITYADMIN;
GRANT SELECT ON VIEW  PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY TO ROLE PORTPILOT_OPS_ANALYST;
GRANT SELECT ON VIEW  PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY TO ROLE PORTPILOT_CUSTOMER_SUCCESS;
GRANT SELECT ON VIEW  PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY TO ROLE PORTPILOT_EXEC;
GRANT SELECT ON VIEW  PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY TO ROLE PORTPILOT_AUDITOR;
GRANT SELECT ON VIEW  PORTPILOT.SEMANTIC.V_DELAY_EVENT TO ROLE PORTPILOT_OPS_ANALYST;
GRANT SELECT ON TABLE PORTPILOT.SEMANTIC.EVENT_VOLUME_DAILY TO ROLE PORTPILOT_OPS_ANALYST;

-- ---------- DEMO RESULTS (screenshot these) ----------
USE ROLE PORTPILOT_ENGINEER;
USE WAREHOUSE PORTPILOT_WH;

SELECT 'journeys' t, COUNT(*) n FROM PORTPILOT.RAW.FACT_CONTAINER_JOURNEY
UNION ALL SELECT 'events', COUNT(*) FROM PORTPILOT.RAW.FACT_CONTAINER_EVENT;

-- Truth #1/#6: APAC OTD dips in week 33
SELECT iso_week, ROUND(100*AVG(on_time_delivery),1) AS otd_pct
FROM PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY
WHERE trade_lane IN ('APAC_DOMESTIC','NORTH_ASIA','TRANS_TASMAN') AND iso_week BETWEEN 30 AND 36
GROUP BY 1 ORDER BY 1;

-- Week-33 causes
SELECT cause_code, COUNT(*) AS events FROM PORTPILOT.SEMANTIC.V_DELAY_EVENT
WHERE iso_week = 33 AND trade_lane IN ('APAC_DOMESTIC','NORTH_ASIA','TRANS_TASMAN')
GROUP BY 1 ORDER BY 2 DESC;

-- Truth #5: Rotterdam GATE_OUT = 0 on Sep 1-3, other feeds steady
SELECT event_day,
  SUM(IFF(source_system='TOS_ROTTERDAM' AND event_type='GATE_OUT', event_count, 0)) AS rotterdam_gate_out,
  SUM(IFF(source_system<>'TOS_ROTTERDAM' AND event_type='GATE_OUT', event_count, 0)) AS other_gate_out
FROM PORTPILOT.SEMANTIC.EVENT_VOLUME_DAILY
WHERE event_day BETWEEN '2026-08-31' AND '2026-09-04' GROUP BY 1 ORDER BY 1;

-- Governance: same view, two roles
USE SECONDARY ROLES NONE;
USE ROLE PORTPILOT_OPS_ANALYST;
SELECT CURRENT_ROLE() r, COUNT(DISTINCT customer_id) customers, MAX(contact_email) email FROM PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY;
USE ROLE PORTPILOT_CUSTOMER_SUCCESS;
SELECT CURRENT_ROLE() r, COUNT(DISTINCT customer_id) customers, MAX(contact_email) email FROM PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY;
