
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS PORTPILOT_OPS_ANALYST;
CREATE ROLE IF NOT EXISTS PORTPILOT_CUSTOMER_SUCCESS;
CREATE ROLE IF NOT EXISTS PORTPILOT_EXEC;
CREATE ROLE IF NOT EXISTS PORTPILOT_AUDITOR;
CREATE ROLE IF NOT EXISTS PORTPILOT_ENGINEER;

GRANT ROLE PORTPILOT_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE PORTPILOT_OPS_ANALYST TO ROLE PORTPILOT_ENGINEER;
GRANT ROLE PORTPILOT_CUSTOMER_SUCCESS TO ROLE PORTPILOT_ENGINEER;
GRANT ROLE PORTPILOT_EXEC TO ROLE PORTPILOT_ENGINEER;
GRANT ROLE PORTPILOT_AUDITOR TO ROLE PORTPILOT_ENGINEER;

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS PORTPILOT;

CREATE SCHEMA IF NOT EXISTS PORTPILOT.RAW;
CREATE SCHEMA IF NOT EXISTS PORTPILOT.CURATED;
CREATE SCHEMA IF NOT EXISTS PORTPILOT.MARTS;
CREATE SCHEMA IF NOT EXISTS PORTPILOT.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS PORTPILOT.GOVERNANCE;

CREATE WAREHOUSE IF NOT EXISTS PORTPILOT_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS PORTPILOT_LOAD_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE TABLE IF NOT EXISTS PORTPILOT.GOVERNANCE.AGENT_AUDIT (
  turn_id STRING,
  thread_id STRING,
  asked_at TIMESTAMP_NTZ,
  role_used STRING,
  question STRING,
  tools_called ARRAY,
  sql_generated STRING,
  docs_cited ARRAY,
  latency_ms NUMBER,
  verdict STRING
);

USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS PORTPILOT_RM
  WITH CREDIT_QUOTA = 35
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 50 PERCENT DO NOTIFY
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS PORTPILOT_LOAD_RM
  WITH CREDIT_QUOTA = 15
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 50 PERCENT DO NOTIFY
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE PORTPILOT_WH SET RESOURCE_MONITOR = PORTPILOT_RM;
ALTER WAREHOUSE PORTPILOT_LOAD_WH SET RESOURCE_MONITOR = PORTPILOT_LOAD_RM;

USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE PORTPILOT_WH TO ROLE PORTPILOT_OPS_ANALYST;
GRANT USAGE ON WAREHOUSE PORTPILOT_WH TO ROLE PORTPILOT_CUSTOMER_SUCCESS;
GRANT USAGE ON WAREHOUSE PORTPILOT_WH TO ROLE PORTPILOT_EXEC;
GRANT USAGE ON WAREHOUSE PORTPILOT_WH TO ROLE PORTPILOT_AUDITOR;
GRANT USAGE ON WAREHOUSE PORTPILOT_WH TO ROLE PORTPILOT_ENGINEER;
GRANT USAGE ON WAREHOUSE PORTPILOT_LOAD_WH TO ROLE PORTPILOT_ENGINEER;

GRANT USAGE ON DATABASE PORTPILOT TO ROLE PORTPILOT_OPS_ANALYST;
GRANT USAGE ON DATABASE PORTPILOT TO ROLE PORTPILOT_CUSTOMER_SUCCESS;
GRANT USAGE ON DATABASE PORTPILOT TO ROLE PORTPILOT_EXEC;
GRANT USAGE ON DATABASE PORTPILOT TO ROLE PORTPILOT_AUDITOR;

GRANT USAGE ON SCHEMA PORTPILOT.SEMANTIC TO ROLE PORTPILOT_OPS_ANALYST;
GRANT USAGE ON SCHEMA PORTPILOT.SEMANTIC TO ROLE PORTPILOT_CUSTOMER_SUCCESS;
GRANT USAGE ON SCHEMA PORTPILOT.SEMANTIC TO ROLE PORTPILOT_EXEC;
GRANT USAGE ON SCHEMA PORTPILOT.SEMANTIC TO ROLE PORTPILOT_AUDITOR;
GRANT USAGE ON SCHEMA PORTPILOT.GOVERNANCE TO ROLE PORTPILOT_AUDITOR;

-- Standard edition: functional roles read only approved secure views in SEMANTIC.

-- Cortex Search is deferred; grant service access when it is implemented.
-- GRANT USAGE ON FUTURE CORTEX SEARCH SERVICES IN SCHEMA PORTPILOT.SEMANTIC TO ROLE PORTPILOT_OPS_ANALYST;
-- GRANT USAGE ON FUTURE CORTEX SEARCH SERVICES IN SCHEMA PORTPILOT.SEMANTIC TO ROLE PORTPILOT_CUSTOMER_SUCCESS;
-- GRANT USAGE ON FUTURE CORTEX SEARCH SERVICES IN SCHEMA PORTPILOT.SEMANTIC TO ROLE PORTPILOT_EXEC;
-- GRANT USAGE ON FUTURE CORTEX SEARCH SERVICES IN SCHEMA PORTPILOT.SEMANTIC TO ROLE PORTPILOT_AUDITOR;

GRANT SELECT ON TABLE PORTPILOT.GOVERNANCE.AGENT_AUDIT TO ROLE PORTPILOT_AUDITOR;

-- Keep database, schemas, table, and both warehouses under the engineering role.
GRANT OWNERSHIP ON DATABASE PORTPILOT
  TO ROLE PORTPILOT_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PORTPILOT.RAW
  TO ROLE PORTPILOT_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PORTPILOT.CURATED
  TO ROLE PORTPILOT_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PORTPILOT.MARTS
  TO ROLE PORTPILOT_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PORTPILOT.SEMANTIC
  TO ROLE PORTPILOT_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PORTPILOT.GOVERNANCE
  TO ROLE PORTPILOT_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE PORTPILOT.GOVERNANCE.AGENT_AUDIT
  TO ROLE PORTPILOT_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE PORTPILOT_WH
  TO ROLE PORTPILOT_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE PORTPILOT_LOAD_WH
  TO ROLE PORTPILOT_ENGINEER COPY CURRENT GRANTS;

GRANT ROLE PORTPILOT_OPS_ANALYST TO USER "YASHASBN";
GRANT ROLE PORTPILOT_CUSTOMER_SUCCESS TO USER "YASHASBN";
GRANT ROLE PORTPILOT_EXEC TO USER "YASHASBN";
GRANT ROLE PORTPILOT_AUDITOR TO USER "YASHASBN";
GRANT ROLE PORTPILOT_ENGINEER TO USER "YASHASBN";

-- Engineer inherits all functional roles; use the functional roles directly
-- when testing secure-view row filtering, not PORTPILOT_ENGINEER.
-- Configure the datagen connection separately for warehouse PORTPILOT_LOAD_WH
-- and role PORTPILOT_ENGINEER so generated-data compute stays attributable.
USE ROLE PORTPILOT_ENGINEER;
USE WAREHOUSE PORTPILOT_WH;

-- Immediate verification. SHOW results are separate result sets by design.
SHOW DATABASES LIKE 'PORTPILOT';

SELECT 'SCHEMA' AS object_type, SCHEMA_NAME AS object_name, CATALOG_NAME AS parent_name
FROM PORTPILOT.INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME IN ('RAW', 'CURATED', 'MARTS', 'SEMANTIC', 'GOVERNANCE')
UNION ALL
SELECT 'TABLE', TABLE_NAME, TABLE_SCHEMA
FROM PORTPILOT.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'GOVERNANCE' AND TABLE_NAME = 'AGENT_AUDIT'
ORDER BY object_type, object_name;

SHOW WAREHOUSES LIKE 'PORTPILOT%';
SHOW ROLES LIKE 'PORTPILOT%';

USE ROLE ACCOUNTADMIN;
SHOW RESOURCE MONITORS LIKE 'PORTPILOT%';

USE ROLE PORTPILOT_ENGINEER;