-- Customer-visible semantic surface.
-- CUSTOMER_ACCESS is intentionally empty by default: populate explicit role/customer
-- mappings before granting this view to PORTPILOT_CUSTOMER_SUCCESS.
CREATE TABLE IF NOT EXISTS PORTPILOT.GOVERNANCE.CUSTOMER_ACCESS (
  role_name STRING NOT NULL,
  customer_id STRING NOT NULL,
  CONSTRAINT CUSTOMER_ACCESS_PK PRIMARY KEY (role_name, customer_id)
);

INSERT INTO PORTPILOT.GOVERNANCE.CUSTOMER_ACCESS (role_name, customer_id)
VALUES
  ('PORTPILOT_CUSTOMER_SUCCESS', 'MERIDIAN_CHEMICALS_GMBH'),
  ('PORTPILOT_CUSTOMER_SUCCESS', 'CUSTOMER_002'),
  ('PORTPILOT_CUSTOMER_SUCCESS', 'CUSTOMER_003');

CREATE SECURE VIEW PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY AS
SELECT
  journey.container_id,
  journey.trade_lane,
  journey.on_time_delivery,
  journey.customer_id,
  CASE
    WHEN IS_ROLE_IN_SESSION('PORTPILOT_AUDITOR')
      OR IS_ROLE_IN_SESSION('PORTPILOT_OPS_ANALYST')
      THEN customer.contact_email
    ELSE '***MASKED***'
  END AS contact_email
FROM PORTPILOT.MARTS.FACT_CONTAINER_JOURNEY AS journey
JOIN PORTPILOT.CURATED.DIM_CUSTOMER AS customer
  ON customer.customer_id = journey.customer_id
WHERE IS_ROLE_IN_SESSION('PORTPILOT_OPS_ANALYST')
   OR IS_ROLE_IN_SESSION('PORTPILOT_EXEC')
   OR IS_ROLE_IN_SESSION('PORTPILOT_AUDITOR')
   OR EXISTS (
     SELECT 1
     FROM PORTPILOT.GOVERNANCE.CUSTOMER_ACCESS AS access
     WHERE access.customer_id = journey.customer_id
       AND access.role_name = CURRENT_ROLE()
   );

-- Keep functional roles on this secure view rather than base tables.
GRANT SELECT ON VIEW PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY TO ROLE PORTPILOT_OPS_ANALYST;
GRANT SELECT ON VIEW PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY TO ROLE PORTPILOT_CUSTOMER_SUCCESS;
GRANT SELECT ON VIEW PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY TO ROLE PORTPILOT_EXEC;
GRANT SELECT ON VIEW PORTPILOT.SEMANTIC.V_CONTAINER_JOURNEY TO ROLE PORTPILOT_AUDITOR;
