-- ============================================================================
-- 06_streamlit_app.sql : Deploy PortPilot AI Streamlit in Snowflake (SiS)
-- ============================================================================
ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = TRUE;

-- 1. Session Context
USE ROLE PORTPILOT_ENGINEER;
USE WAREHOUSE PORTPILOT_WH;
USE DATABASE PORTPILOT;
USE SCHEMA SEMANTIC;

-- 2. Create internal stage for application code and environment definition
CREATE STAGE IF NOT EXISTS PORTPILOT.SEMANTIC.PORTPILOT_APP_STAGE
  DIRECTORY = (ENABLE = TRUE);

-- 3. File Upload Commands (to run via SnowSQL or Snowflake CLI from repository root)
-- PUT file://streamlit/app.py @PORTPILOT.SEMANTIC.PORTPILOT_APP_STAGE/ OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
-- PUT file://streamlit/environment.yml @PORTPILOT.SEMANTIC.PORTPILOT_APP_STAGE/ OVERWRITE = TRUE AUTO_COMPRESS = FALSE;

-- 4. Create or Replace Streamlit Application Object in Snowflake
CREATE OR REPLACE STREAMLIT PORTPILOT.SEMANTIC.PORTPILOT_APP
  ROOT_LOCATION = '@PORTPILOT.SEMANTIC.PORTPILOT_APP_STAGE'
  MAIN_FILE = 'app.py'
  QUERY_WAREHOUSE = PORTPILOT_WH
  COMMENT = 'PortPilot AI Governed Supply-Chain Operations Command Center';

-- 5. Grant Usage on Application to Functional Roles
USE ROLE SECURITYADMIN;

GRANT USAGE ON STREAMLIT PORTPILOT.SEMANTIC.PORTPILOT_APP TO ROLE PORTPILOT_OPS_ANALYST;
GRANT USAGE ON STREAMLIT PORTPILOT.SEMANTIC.PORTPILOT_APP TO ROLE PORTPILOT_CUSTOMER_SUCCESS;
GRANT USAGE ON STREAMLIT PORTPILOT.SEMANTIC.PORTPILOT_APP TO ROLE PORTPILOT_EXEC;
GRANT USAGE ON STREAMLIT PORTPILOT.SEMANTIC.PORTPILOT_APP TO ROLE PORTPILOT_AUDITOR;

-- 6. Switch back to Engineer role for verification
USE ROLE PORTPILOT_ENGINEER;
USE WAREHOUSE PORTPILOT_WH;

SHOW STREAMLITS LIKE 'PORTPILOT_APP' IN SCHEMA PORTPILOT.SEMANTIC;
